"""add ticket_create_date, chenge ticket_ticket_type

Revision ID: 1b3b257daa2b
Revises: 58b81ae8a4f4
Create Date: 2025-12-21 07:50:53.264166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b3b257daa2b'
down_revision = '58b81ae8a4f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('create_time', sa.DateTime(), nullable=False))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('create_time')
        batch_op.drop_column('ticket_type')

    # ### end Alembic commands ###
