"""Initial migration

Revision ID: 58b81ae8a4f4
Revises: 
Create Date: 2025-09-17 02:56:24.901213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58b81ae8a4f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chip_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=True),
    sa.Column('chip_before', sa.Integer(), nullable=False),
    sa.Column('chip_after', sa.Integer(), nullable=False),
    sa.Column('point_before', sa.Integer(), nullable=False),
    sa.Column('point_after', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=True),
    sa.Column('user_username', sa.String(length=20), nullable=True),
    sa.Column('user_pw', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('pw', sa.String(length=20), nullable=False),
    sa.Column('chip', sa.Integer(), nullable=True),
    sa.Column('point', sa.Integer(), nullable=True),
    sa.Column('last_login', sa.Date(), nullable=True),
    sa.Column('station', sa.String(length=20), nullable=True),
    sa.Column('fare', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('ticket')
    op.drop_table('chip_log')
    # ### end Alembic commands ###
