"""add_1

Revision ID: c9e9e7535d69
Revises: 1b3b257daa2b
Create Date: 2025-12-21 10:03:44.240269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9e9e7535d69'
down_revision = '1b3b257daa2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('ticket_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('create_time',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('ticket_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
